development:
  adapter: sqlserver
  host: localhost
  database: esencialverdesystem
  username: sa
  password: Sven1234

test:
  adapter: sqlserver
  host: localhost
  database: esencialverdesystem
  username: sa
  password: Sven1234
